In [4]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns

In [5]:
from ucimlrepo import fetch_ucirepo

heart_disease = fetch_ucirepo(id=45)  # UCI Heart Disease dataset
heart_df = heart_disease.data.features
heart_target = heart_disease.data.targets
heart_metadata = heart_disease.metadata

heart_df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
0,63,1,1,145,233,1,2,150,0,2.3,3,0.0,6.0
1,67,1,4,160,286,0,2,108,1,1.5,2,3.0,3.0
2,67,1,4,120,229,0,2,129,1,2.6,2,2.0,7.0
3,37,1,3,130,250,0,0,187,0,3.5,3,0.0,3.0
4,41,0,2,130,204,0,2,172,0,1.4,1,0.0,3.0

In [6]:
import types

import requests

# Fetch module code from URL
url = "https://raw.githubusercontent.com/jhlopesalves/data-science-notebooks/main/Python/projects/ames_house/data/missing_summary.py"
response = requests.get(url)  # Send HTTP GET request
response.raise_for_status()  # Raise exception for HTTP errors

module_code = response.text  # Extract response text

# Create new module object
mod = types.ModuleType("missing_summary")
# Execute module code in module's namespace
exec(module_code, mod.__dict__)

# Call function from imported module
mod.missing_data_summary(heart_df)

     Data Type  Missing Count  Missing %  Non-Missing Count
ca     float64              4       1.32                299
thal   float64              2       0.66                301