# Women's E-Commerce Clothing Reviews

## Dataset Overview

This dataset contains **23,486 customer reviews** with **10 features** per review.

## Feature Description

| Variable | Type | Description |
|----------|------|-------------|
| **Clothing ID** | Integer (Categorical) | Unique identifier for the specific clothing item being reviewed |
| **Age** | Positive Integer | Age of the reviewer |
| **Title** | String | Title of the review |
| **Review Text** | String | Main body/content of the review |
| **Rating** | Positive Ordinal Integer (1-5) | Product rating where 1 = Worst, 5 = Best |
| **Recommended IND** | Binary (0/1) | Recommendation indicator: 1 = Recommended, 0 = Not Recommended |
| **Positive Feedback Count** | Positive Integer | Number of other customers who found this review helpful |
| **Division Name** | Categorical | High-level product division category |
| **Department Name** | Categorical | Product department category |
| **Class Name** | Categorical | Specific product class/category |

## Basic Stack

In [12]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns

## Loading dataset

In [13]:
url = "https://raw.githubusercontent.com/jhlopesalves/data-science-notebooks/refs/heads/main/Python/projects/womens_ecommerce/data/Womens%20Clothing%20E-Commerce%20Reviews.csv"
womens_df = pd.read_csv(url, usecols=lambda col: not col.startswith("Unnamed"))

## Basic EDA (inspection)

In [14]:
womens_df

,Clothing ID,Age,Title,Review Text,Rating,Recommended IND,Positive Feedback Count,Division Name,Department Name,Class Name
0,767,33,NaN,Absolutely wonderful - silky and sexy and comf...,4,1,0,Initmates,Intimate,Intimates
1,1080,34,NaN,Love this dress! it's sooo pretty. i happene...,5,1,4,General,Dresses,Dresses
2,1077,60,Some major design flaws,I had such high hopes for this dress and reall...,3,0,0,General,Dresses,Dresses
3,1049,50,My favorite buy!,"I love, love, love this jumpsuit. it's fun, fl...",5,1,0,General Petite,Bottoms,Pants
4,847,47,Flattering shirt,This shirt is very flattering to all due to th...,5,1,6,General,Tops,Blouses
...,...,...,...,...,...,...,...,...,...,...
23481,1104,34,Great dress for many occasions,I was very happy to snag this dress at such a ...,5,1,0,General Petite,Dresses,Dresses
23482,862,48,Wish it was made of cotton,"It reminds me of maternity clothes. soft, stre...",3,1,0,General Petite,Tops,Knits
23483,1104,31,"Cute, but see through","This fit well, but the top was very see throug...",3,0,1,General Petite,Dresses,Dresses
23484,1084,28,"Very cute dress, perfect for summer parties an...",I bought this dress for a wedding i have this ...,3,1,2,General,Dresses,Dresses
23485,1104,52,Please make more like this one!,This dress in a lovely platinum is feminine an...,5,1,22,General Petite,Dresses,Dresses

In [15]:
womens_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23486 entries, 0 to 23485
Data columns (total 10 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Clothing ID              23486 non-null  int64
 1   Age                      23486 non-null  int64
 2   Title                    19676 non-null  object
 3   Review Text              22641 non-null  object
 4   Rating                   23486 non-null  int64
 5   Recommended IND          23486 non-null  int64
 6   Positive Feedback Count  23486 non-null  int64
 7   Division Name            23472 non-null  object
 8   Department Name          23472 non-null  object
 9   Class Name               23472 non-null  object
dtypes: int64(5), object(5)
memory usage: 1.8+ MB

In [16]:
womens_df.describe()

,Clothing ID,Age,Rating,Recommended IND,Positive Feedback Count
count,23486.000000,23486.000000,23486.000000,23486.000000,23486.000000
mean,918.118709,43.198544,4.196032,0.822362,2.535936
std,203.298980,12.279544,1.110031,0.382216,5.702202
min,0.000000,18.000000,1.000000,0.000000,0.000000
25%,861.000000,34.000000,4.000000,1.000000,0.000000
50%,936.000000,41.000000,5.000000,1.000000,1.000000
75%,1078.000000,52.000000,5.000000,1.000000,3.000000
max,1205.000000,99.000000,5.000000,1.000000,122.000000

## Missingness

In [17]:
womens_df.isna().sum().sort_values(ascending=False)

Title                      3810
Review Text                 845
Class Name                   14
Division Name                14
Department Name              14
Clothing ID                   0
Age                           0
Rating                        0
Recommended IND               0
Positive Feedback Count       0
dtype: int64

## Missingness: 'Class Name'

In [18]:
missing_mask_class = womens_df["Class Name"].isna()

womens_df.loc[
    missing_mask_class,
    ["Clothing ID", "Age", "Rating", "Positive Feedback Count", "Title", "Review Text"],
]

,Clothing ID,Age,Rating,Positive Feedback Count,Title,Review Text
9444,72,25,5,0,My favorite socks!!!,"I never write reviews, but these socks are so ..."
13767,492,23,5,1,So soft!,I just love this hoodie! it is so soft and com...
13768,492,49,5,0,Wardrobe staple,Love this hoodie. so soft and goes with everyt...
13787,492,48,5,0,NaN,NaN
16216,152,36,5,0,Warm and cozy,"Just what i was looking for. soft, cozy and warm."
16221,152,37,5,0,Love!,I am loving these. they are quite long but are...
16223,152,39,5,0,"""long and warm""",These leg warmers are perfect for me. they are...
18626,184,34,5,5,Nubby footless tights,"These are amazing quality. i agree, size up to..."
18671,184,54,5,0,New workhorse,These tights are amazing! if i care for them w...
20088,772,50,5,0,Comfy sweatshirt!,This sweatshirt is really nice! it's oversize...
21532,665,43,5,0,So worth it!,Got these on sale...absolutely love eberjey! f...
22997,136,47,5,1,"Charcoal, pale gray, a bit of silver!","These socks are soft and comfortable, and they..."
23006,136,33,5,0,Cute itsy socks,"Love polkadots, love sparkle. these little soc..."
23011,136,36,5,0,Super socks,I love these little socks ? and the dots spark...

In [19]:
missing_class_ids = womens_df.loc[missing_mask_class, "Clothing ID"].unique()


womens_df[womens_df["Clothing ID"].isin(missing_class_ids)].groupby("Clothing ID")[
    ["Division Name", "Department Name", "Class Name"]
].nunique()

             Division Name  Department Name  Class Name
Clothing ID
72                       0                0           0
136                      0                0           0
152                      0                0           0
184                      0                0           0
492                      0                0           0
665                      0                0           0
772                      0                0           0

## Missingness: Review Text

In [20]:
missing_review_text = womens_df["Review Text"].isna()

womens_df.loc[
    missing_review_text,
    ["Clothing ID", "Age", "Rating", "Positive Feedback Count", "Title"],
]

       Clothing ID  Age  Rating  Positive Feedback Count Title
92             861   23       5                        0   NaN
93            1081   31       5                        0   NaN
98            1133   50       5                        0   NaN
135            861   35       4                        0   NaN
142           1126   35       5                        0   NaN
...            ...  ...     ...                      ...   ...
23258          862   35       4                        0   NaN
23301          862   52       5                        0   NaN
23303          823   46       5                        0   NaN
23470         1104   39       5                        0   NaN
23480          862   35       5                        0   NaN

[845 rows x 5 columns]

In [ ]:
missing_review_ids = womens_df.loc[missing_review_text, "Clothing ID"].unique()

womens_df[womens_df["Clothing ID"].isin(missing_review_ids)].groupby("Clothing ID")[
    ["Rating", "Recommended IND"]
].nunique().sort_values(by="Rating", ascending=False)

             Rating  Recommended IND
Clothing ID
834               5                2
835               5                2
823               5                2
824               5                2
828               5                2
...             ...              ...
302               1                1
1067              1                1
1029              1                1
1181              1                1
1164              1                1

[248 rows x 2 columns]

In [31]:
present_review_text = womens_df["Review Text"].notna()

womens_df.loc[
    present_review_text,
    ["Clothing ID", "Age", "Rating", "Positive Feedback Count", "Title"],
]

,Clothing ID,Age,Rating,Positive Feedback Count,Title
0,767,33,4,0,NaN
1,1080,34,5,4,NaN
2,1077,60,3,0,Some major design flaws
3,1049,50,5,0,My favorite buy!
4,847,47,5,6,Flattering shirt
...,...,...,...,...,...
23481,1104,34,5,0,Great dress for many occasions
23482,862,48,3,0,Wish it was made of cotton
23483,1104,31,3,1,"Cute, but see through"
23484,1084,28,3,2,"Very cute dress, perfect for summer parties an..."
23485,1104,52,5,22,Please make more like this one!

In [33]:
ids_with_no_missing_reviews = ~womens_df["Clothing ID"].isin(missing_review_ids)

womens_df[ids_with_no_missing_reviews].groupby("Clothing ID")[
    ["Rating", "Recommended IND"]
].nunique().sort_values(by="Rating", ascending=False)

             Rating  Recommended IND
Clothing ID
832               5                2
1084              5                2
977               5                2
1016              5                2
1039              5                2
...             ...              ...
1199              1                1
1200              1                1
367               1                1
369               1                1
19                1                1

[958 rows x 2 columns]